sudo: required
language: node_js
node_js:
  - "node"

addons:
  srcclr: true

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  slack: bipioteam:1TUQcmvbfrbxWwxViLG4ybAA

before_install:
  - "yarn global add eslint"
  - "yarn global add snyk"

install:
  - NODE_ENV=development yarn install

script:
  - snyk auth $SNYK_AUTH_TOKEN
  - npm run js:lint
  - npm run test:all
