sudo: required
language: node_js
node_js:
  - "node"

addons:
  srcclr: true

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  slack: bipioteam:1TUQcmvbfrbxWwxViLG4ybAA

before_install:
  - "npm install -g eslint"
  - "npm install -g eslint-config-airbnb-base"
  - "npm install -g install-peerdeps"
  - "npm install -g eslint-plugin-security"
  - "install-peerdeps --dev eslint-config-airbnb-base"
  - "npm install -g mocha chai babel-cli"
  - "npm install -g snyk"

install:
  - npm install

script:
  - snyk auth $SNYK_AUTH_TOKEN
  - npm run js:lint:dev
  - npm run test:all
  - npm run build
