version: '2'

services:
  node:
    image: core
    container_name: biphub-dev
    environment:
        NODE_ENV: development
        SERVER_URL: 192.168.99.100
        FORWARDED_PORT: 3000
    build:
      context: .
      dockerfile: .docker/node.dev.dockerfile
    volumes:
      - .:/core
      - /core/node_modules
    ports:
      - "3000:8080"