#!/bin/bash -e

SESSION=dev

tmux new-session -d -s $SESSION
tmux new-window -t $SESSION:1 -n 'biphub'

tmux select-window -t $SESSION:1
tmux send-keys 'vim test1' C-m
tmux split-window -h
tmux send-keys 'vim test2' C-m
tmux split-window -v

tmux attach -t $SESSION

