#!/bin/bash -e

SESSION=dev

tmux new-session -d -s $SESSION
tmux new-window -t $SESSION:1 -n 'biphub'

tmux select-window -t $SESSION:1
tmux send-keys 'bash ./scripts/dev'
tmux split-window -v
tmux send-keys 'bash ./scripts/lint/watch'

tmux attach -t $SESSION
