#!/bin/bash -e

TAG="bipflow:$LOGNAME"
docker build --tag="$TAG" \
  --file="./.docker/node.dev.dockerfile" \
  "."

docker run -it -v "$(pwd):/home/node/app" -v "/home/node/app/node_modules" $TAG \
 yarn js:lint:watch
